SELECT
     OFERTA.IDOFERTA,
     OFERTA.IDTIENDA,
     OFERTA.IDPRODUCTO,
     OFERTA.NOMBREOFERTA,
     OFERTA.MINIMOPRODUCTO,
     OFERTA.MAXIMOPRODUCTO,
     OFERTA.PRECIOOFERTA,
     OFERTA.DESCUENTOOFERTA,
     OFERTA.STOCKPRODUCTOOFERTA,
     OFERTA.IDESTADO,
     OFERTA.IMAGENOFERTA,
     OFERTA.VISITAS,
     TO_CHAR(OFERTA.FECHAVISITA) ,
     TIENDA.IDTIENDA,
     PRODUCTO.IDPRODUCTO,
     ESTADO.GLOSAESTADO,
     PRODUCTO.NOMBREPRODUCTO,
     ESTADO.IDESTADO,
     TIENDA.NOMBRETIENDA
FROM
     PRODUCTO INNER JOIN OFERTA ON PRODUCTO.IDPRODUCTO = OFERTA.IDPRODUCTO
              INNER JOIN ESTADO ON OFERTA.IDESTADO = ESTADO.IDESTADO
              INNER JOIN TIENDA ON OFERTA.IDTIENDA = TIENDA.IDTIENDA